title: SWONTHEROOF
description: Photography portfolio by SW
about:
  bio: "A photographer."
  cameras:
    - FUJIFILM X-E5
    - PENTAX ME SUPER
instagram_username: paintingsbylight
instagram_url: "https://www.instagram.com/paintingsbylight/"
url: "https://swontheroof.github.io"
baseurl: ""
exclude:
  - README.md
